### PR TITLE
Add landing message. #1

### PR DESCRIPTION
**Pull request by migreydev**

### CODE REVIEW

**Review by Smartin0312 — COMMENTED** [review]
could you remove the "enjoy you stay." string and make the "Welcome to Potionfy!" string red?

**Comment by migreydev** [comment]
sure can do

**Comment by Smartin0312** [comment]
index.html

**Review by Smartin0312 — COMMENTED** [review]
index.txt

**Comment by Smartin0312** [comment]
please , change the code as per my comment on the review

**Review by Smartin0312 — COMMENTED** [review]
development/index.html

**Review by Smartin0312 — COMMENTED** [review]
well done Harry!

**Pull request merged**
